# Generated by Django 3.0.7 on 2020-06-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='identifier',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='number',
            field=models.CharField(max_length=32, verbose_name='key_number'),
        ),
        migrations.AlterField(
            model_name='lockingsystem',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=32, verbose_name='room_number'),
        ),
    ]
