# Generated by Django 3.1.3 on 2020-11-09 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='keys',
            new_name='key',
        ),
    ]
