# Generated by Django 3.1.3 on 2021-01-09 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='issue',
            name='active_dont_have_in_date',
        ),
        migrations.RemoveConstraint(
            model_name='issue',
            name='inactive_has_in_date',
        ),
        migrations.AlterField(
            model_name='issue',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='key',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('issues__active', False), ('stolen_or_lost', False)), models.Q(('issues__isnull', True), ('stolen_or_lost', False)), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='keys.key', verbose_name='Schlüssel'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('active', True), ('in_date__isnull', True)), models.Q(('active', False), ('in_date__isnull', False)), _connector='OR'), name='only_inacrive_have_in_date'),
        ),
    ]
