# Generated by Django 3.2a1 on 2021-02-03 16:59

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='group',
            managers=[
                ('all_groups', django.db.models.manager.Manager()),
            ],
        ),
    ]
