# Generated by Django 3.0.7 on 2020-07-02 15:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='out_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 2, 15, 18, 22, 207922, tzinfo=utc), verbose_name='Ausgabedatum'),
        ),
    ]
