# Generated by Django 3.1.3 on 2020-11-30 11:06

import datetime
from django.db import migrations, models
import keys.models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='amount_currency',
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5, verbose_name='Kautionsbetrag'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='in_datetime',
            field=models.DateTimeField(default=datetime.datetime.now, validators=[keys.models.present_or_max_3_days_ago], verbose_name='Einzahlungszeitpunkt'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='in_method',
            field=models.CharField(choices=[('cash', 'Bargeld'), ('bank transfer', 'Überweisung'), ('other payment provider', 'anderer Zahlungsdienstleister')], max_length=64, verbose_name='Einzahlungsmittel'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='out_datetime',
            field=models.DateTimeField(blank=True, null=True, validators=[keys.models.present_or_max_3_days_ago], verbose_name='Rückzahlungszeitpunkt'),
        ),
    ]
