# Generated by Django 3.1.5 on 2021-01-27 17:14

from django.db import migrations, models
import keys.validators


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=50, max_digits=5, validators=[keys.validators.validate_deposit_mail], verbose_name='Betrag'),
        ),
    ]
