# Generated by Django 3.1.3 on 2021-01-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Kommentar'),
        ),
    ]
