# Generated by Django 3.1.5 on 2021-02-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='key',
        ),
        migrations.AddField(
            model_name='issue',
            name='key',
            field=models.ManyToManyField(related_name='issues', to='keys.Key', verbose_name='Schlüssel'),
        ),
    ]
