# Generated by Django 3.1.3 on 2021-01-28 14:04

import autoslug.fields
from django.db import migrations
import keys.models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=keys.models.get_populate_from),
        ),
    ]
