# Generated by Django 3.0.7 on 2020-07-06 17:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='out_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 6, 17, 23, 0, 188141, tzinfo=utc), verbose_name='Ausgabedatum'),
        ),
    ]
