# Generated by Django 3.1.3 on 2021-01-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0002_issue_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='comment',
            field=models.CharField(blank=True, error_messages={'max_length': 'Bitte nicht mehr als 500 Zeichen pro Kommentar'}, max_length=500, null=True, verbose_name='Kommentar'),
        ),
    ]
