# Generated by Django 3.0.7 on 2020-07-07 12:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0002_auto_20200706_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='key',
            options={'ordering': ['locking_system', 'number'], 'verbose_name': 'Schlüssel', 'verbose_name_plural': 'Schlüssel'},
        ),
        migrations.RemoveConstraint(
            model_name='key',
            name='key_number+locking_system_is_unique',
        ),
        migrations.RenameField(
            model_name='door',
            old_name='locking_system_door',
            new_name='locking_system',
        ),
        migrations.RenameField(
            model_name='key',
            old_name='locking_system_key',
            new_name='locking_system',
        ),
        migrations.AlterField(
            model_name='issue',
            name='out_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 7, 12, 28, 8, 178847, tzinfo=utc), verbose_name='Ausgabedatum'),
        ),
        migrations.AddConstraint(
            model_name='key',
            constraint=models.UniqueConstraint(fields=('number', 'locking_system'), name='key_number+locking_system_is_unique'),
        ),
    ]
