# Generated by Django 3.1.3 on 2020-11-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0002_auto_20201130_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='currency',
            field=models.CharField(choices=[('EUR', '€')], default='EUR', max_length=3, verbose_name='Währung'),
        ),
    ]
