# Generated by Django 3.0.7 on 2020-11-06 16:18

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0002_auto_20201106_1709'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='issue',
            managers=[
                ('person', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='issue',
            name='person+key_is_unique',
        ),
    ]
