# Generated by Django 3.0.7 on 2020-11-09 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0002_auto_20201109_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='keys',
            new_name='key',
        ),
        migrations.AlterField(
            model_name='issue',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='keys.Person', verbose_name='Ausgaben'),
        ),
    ]
