# Generated by Django 3.1.5 on 2021-01-28 20:15

import autoslug.fields
from django.db import migrations
import keys.models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0002_auto_20210128_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=keys.models.get_populate_from, unique=True),
        ),
    ]
