# Generated by Django 3.0.7 on 2020-06-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0002_auto_20200623_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
