# Generated by Django 3.0.7 on 2020-07-01 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0002_auto_20200701_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 22, 25, 52, 180125), verbose_name='Erstellungszeitpunkt'),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 22, 25, 52, 180141), verbose_name='Aktualisierungszeitpunkt'),
        ),
    ]
