# Generated by Django 3.1.5 on 2021-01-30 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0002_auto_20210129_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='keys.person', verbose_name='Person'),
        ),
    ]
