# Generated by Django 3.0.7 on 2020-07-01 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0003_auto_20200701_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 22, 30, 27, 120004), verbose_name='Erstellungszeitpunkt'),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 22, 30, 27, 120021), verbose_name='Aktualisierungszeitpunkt'),
        ),
    ]
