# Generated by Django 3.1.3 on 2021-01-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0003_auto_20210118_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='door',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='lockingsystem',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Kommentar'),
        ),
    ]
