# Generated by Django 3.1.5 on 2021-01-30 11:09

from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0003_auto_20210130_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='keys.person', verbose_name='Person'),
        ),
        migrations.AddConstraint(
            model_name='deposit',
            constraint=models.UniqueConstraint(condition=models.Q(state='in'), fields=('person',), name='only_one_active_deposit'),
        ),
    ]
