# Generated by Django 3.1.3 on 2020-11-30 19:55

from django.db import migrations, models
import django.utils.timezone
import keys.models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0003_deposit_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='in_method',
            field=models.CharField(choices=[('cash', 'Bar'), ('bank transfer', 'Überweisung')], default='cash', max_length=64, verbose_name='Zahlungsmittel'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='out_method',
            field=models.CharField(choices=[('cash', 'Bar'), ('bank transfer', 'Überweisung')], default='cash', max_length=64, null=True, verbose_name='Zahlungsmittel'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='in_date',
            field=models.DateField(default=django.utils.timezone.now, null=True, validators=[keys.models.present_or_max_10_days_ago], verbose_name='Rückgabedatum'),
        ),
    ]
