# Generated by Django 3.1.5 on 2021-02-16 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0003_auto_20210216_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='keys.key', verbose_name='Schlüssel'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(condition=models.Q(active=True), fields=('key',), name='key_not_yet_returned'),
        ),
    ]
