# Generated by Django 3.0.7 on 2020-06-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0003_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=32, verbose_name='room number'),
        ),
    ]
