# Generated by Django 3.0.7 on 2020-07-02 19:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0003_auto_20200702_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='deposit',
        ),
        migrations.AddField(
            model_name='person',
            name='deposit_made',
            field=models.BooleanField(default=False, verbose_name='Kaution hinterlegt'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='out_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 2, 19, 59, 29, 679904, tzinfo=utc), verbose_name='Ausgabedatum'),
        ),
    ]
