# Generated by Django 3.1.3 on 2020-11-30 19:58

import datetime
from django.db import migrations, models
import keys.models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0004_auto_20201130_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='out_datetime',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, validators=[keys.models.present_or_max_3_days_ago], verbose_name='Rückzahlungszeitpunkt'),
        ),
    ]
