# Generated by Django 3.1.5 on 2021-01-30 11:23

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0004_auto_20210130_1209'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='deposit',
            managers=[
                ('all_deposits', django.db.models.manager.Manager()),
            ],
        ),
    ]
