# Generated by Django 3.1.5 on 2021-02-26 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0004_auto_20210216_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='keys.person', verbose_name='Person'),
        ),
    ]
