# Generated by Django 3.0.7 on 2020-06-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0004_auto_20200623_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='purpose',
            field=models.CharField(choices=[('committee', 'committee room'), ('storage', 'storage'), ('learning', 'learning space'), ('event', 'event location'), ('multipurpose', 'multipurpose room'), ('other', 'other')], default='comittee', max_length=32),
            preserve_default=False,
        ),
    ]
