# Generated by Django 3.1.3 on 2021-01-18 19:24

from django.db import migrations, models
import keys.validators


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0005_auto_20210118_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='out_datetime',
            field=models.DateTimeField(null=True, validators=[keys.validators.present_or_max_3_days_ago], verbose_name='Rückzahlungszeitpunkt'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='in_date',
            field=models.DateField(blank=True, null=True, validators=[keys.validators.present_or_max_10_days_ago], verbose_name='Rückgabedatum'),
        ),
    ]
