# Generated by Django 3.1.3 on 2020-11-30 20:10

from django.db import migrations, models
import keys.models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0005_auto_20201130_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='in_datetime',
            field=models.DateTimeField(validators=[keys.models.present_or_max_3_days_ago], verbose_name='Einzahlungszeitpunkt'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='out_datetime',
            field=models.DateTimeField(null=True, validators=[keys.models.present_or_max_3_days_ago], verbose_name='Rückzahlungszeitpunkt'),
        ),
    ]
