# Generated by Django 3.0.7 on 2020-07-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0005_auto_20200701_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellungszeitpunkt'),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualisierungszeitpunkt'),
        ),
    ]
