# Generated by Django 3.0.7 on 2020-06-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0005_room_purpose'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('building', 'number'), name='room_is_unique'),
        ),
    ]
