# Generated by Django 3.2a1 on 2021-02-02 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0005_auto_20210130_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='key',
            field=models.ForeignKey(limit_choices_to=models.Q(('issues__have_active', True), ('stolen_or_lost', True), _negated=True), on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='keys.key', verbose_name='Schlüssel'),
        ),
    ]
