# Generated by Django 3.1.5 on 2021-01-19 14:35

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0006_auto_20210118_2024'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='issue',
            name='only_inacrive_have_in_date',
        ),
        migrations.RemoveConstraint(
            model_name='issue',
            name='give_out_before_take_in',
        ),
        migrations.AddField(
            model_name='deposit',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AddConstraint(
            model_name='deposit',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('active', True), ('in_datetime__isnull', True)), models.Q(('active', False), ('in_datetime__isnull', False)), _connector='OR'), name='inactive_deposit_no_in_datetime'),
        ),
        migrations.AddConstraint(
            model_name='deposit',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('active', True), ('in_datetime__isnull', True)), models.Q(('active', False), ('in_datetime__isnull', False)), _connector='OR'), name='inactive_deposit_no_in_method'),
        ),
        migrations.AddConstraint(
            model_name='deposit',
            constraint=models.CheckConstraint(check=models.Q(in_datetime__lte=django.db.models.expressions.F('out_datetime')), name='take_in_before_give_out'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('active', True), ('in_date__isnull', True)), models.Q(('active', False), ('in_date__isnull', False)), _connector='OR'), name='inactive_issue_no_in_date'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.CheckConstraint(check=models.Q(out_date__gte=django.db.models.expressions.F('in_date')), name='give_out_before_take_in'),
        ),
    ]
