# Generated by Django 3.1.3 on 2020-12-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0006_auto_20201130_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Kautionsbetrag'),
        ),
    ]
