# Generated by Django 3.0.7 on 2020-06-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0006_auto_20200623_2051'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lockingsystem',
            constraint=models.UniqueConstraint(fields=('name', 'company'), name='locking_system_is_unique'),
        ),
    ]
