# Generated by Django 3.2a1 on 2021-02-02 22:14

from django.db import migrations, models
import django.db.models.deletion
import keys.validators


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0006_alter_issue_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='in_date',
            field=models.DateField(blank=True, null=True, validators=[keys.validators.present_or_max_10_days_ago], verbose_name='Rückgabedatum'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='key',
            field=models.ForeignKey(limit_choices_to=models.Q(('issues__active', False), ('stolen_or_lost', False)), on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='keys.key', verbose_name='Schlüssel'),
        ),
    ]
