# Generated by Django 3.0.7 on 2020-07-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0006_auto_20200701_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='deposit_paid',
            field=models.BooleanField(default=False, verbose_name='Kaution hinterlegt'),
        ),
    ]
