# Generated by Django 3.1.5 on 2021-03-07 10:50

from django.db import migrations, models
import django_extensions.validators
import keys.validators


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0006_auto_20210227_1233'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='building',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='deposit',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='group',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='issue',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='key',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='person',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='room',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='deposit',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django_extensions.validators.NoControlCharactersValidator, django_extensions.validators.NoWhitespaceValidator], verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django_extensions.validators.NoControlCharactersValidator, django_extensions.validators.NoWhitespaceValidator], verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=64, validators=[django_extensions.validators.NoControlCharactersValidator, django_extensions.validators.NoWhitespaceValidator], verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=64, validators=[django_extensions.validators.NoControlCharactersValidator, django_extensions.validators.NoWhitespaceValidator], verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='person',
            name='university_email',
            field=models.EmailField(max_length=254, unique=True, validators=[keys.validators.validate_university_mail], verbose_name='Uni Mail'),
        ),
    ]
