# Generated by Django 3.1.5 on 2021-01-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0007_auto_20210119_1535'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deposit',
            name='inactive_deposit_no_in_datetime',
        ),
        migrations.AddConstraint(
            model_name='deposit',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('active', True), ('out_datetime__isnull', True)), models.Q(('active', False), ('out_datetime__isnull', False)), _connector='OR'), name='inactive_deposit_no_in_datetime'),
        ),
    ]
