# Generated by Django 3.0.7 on 2020-06-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0007_auto_20200623_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='door',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='doors',
            field=models.ManyToManyField(to='keys.Door'),
        ),
        migrations.AlterField(
            model_name='key',
            name='number',
            field=models.CharField(max_length=32, verbose_name='key number'),
        ),
        migrations.AlterField(
            model_name='room',
            name='purpose',
            field=models.CharField(choices=[('committee', 'Gremienraum'), ('storage', 'Lager'), ('learning', 'Lernraum'), ('multipurpose', 'Mehrzweckraum'), ('other', 'Other')], max_length=32),
        ),
    ]
