# Generated by Django 3.1.5 on 2021-03-17 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.validators
import keys.validators
import phonenumber_field.modelfields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keys', '0007_auto_20210307_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPerson',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('first_name', models.CharField(max_length=64, validators=[django_extensions.validators.NoControlCharactersValidator, django_extensions.validators.NoWhitespaceValidator], verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=64, validators=[django_extensions.validators.NoControlCharactersValidator, django_extensions.validators.NoWhitespaceValidator], verbose_name='Nachname')),
                ('university_email', models.EmailField(db_index=True, max_length=254, validators=[keys.validators.validate_university_mail], verbose_name='Uni Mail')),
                ('private_email', models.EmailField(db_index=True, max_length=254, verbose_name='Private Mail')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, verbose_name='Telefon')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Erstellungszeitpunkt')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Aktualisierungszeitpunkt')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='keys.group', verbose_name='Gruppe')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Person',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalIssue',
            fields=[
                ('active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('out_date', models.DateField(default=django.utils.timezone.now, validators=[keys.validators.present_or_past_date], verbose_name='Ausgabedatum')),
                ('in_date', models.DateField(blank=True, null=True, validators=[keys.validators.present_or_max_10_days_ago], verbose_name='Rückgabedatum')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, validators=[django_extensions.validators.NoControlCharactersValidator, django_extensions.validators.NoWhitespaceValidator], verbose_name='Kommentar')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Erstellungszeitpunkt')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Aktualisierungszeitpunkt')),
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('key', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='keys.key', verbose_name='Schlüssel')),
                ('person', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='keys.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'historical Ausleihe',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDeposit',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.CharField(choices=[('in', 'Eingezahlt'), ('retained', 'Einbehalten'), ('out', 'Ausgezahlt')], default='in', max_length=8, verbose_name='Status')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=50, max_digits=5, validators=[keys.validators.amount_is_not_negative_and_reasonable], verbose_name='Betrag')),
                ('currency', models.CharField(choices=[('EUR', '€')], default='EUR', max_length=3, verbose_name='Währung')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, validators=[django_extensions.validators.NoControlCharactersValidator, django_extensions.validators.NoWhitespaceValidator], verbose_name='Kommentar')),
                ('in_datetime', models.DateTimeField(default=django.utils.timezone.now, validators=[keys.validators.present_or_max_3_days_ago], verbose_name='Einzahlungszeitpunkt')),
                ('in_method', models.CharField(choices=[('cash', 'Bar'), ('bank_transfer', 'Überweisung')], default='cash', max_length=64, verbose_name='Einzahlungsmittel')),
                ('retained_datetime', models.DateTimeField(null=True, validators=[keys.validators.present_or_max_3_days_ago], verbose_name='Einbehaltungszeitpunkt')),
                ('out_datetime', models.DateTimeField(null=True, validators=[keys.validators.present_or_max_3_days_ago], verbose_name='Rückzahlungszeitpunkt')),
                ('out_method', models.CharField(choices=[('cash', 'Bar'), ('bank_transfer', 'Überweisung')], max_length=64, null=True, verbose_name='Auszahlungsmittel')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Erstellungszeitpunkt')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Aktualisierungszeitpunkt')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='keys.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'historical Kaution',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
