# Generated by Django 3.0.7 on 2020-06-23 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0008_auto_20200623_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='doors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='keys.Door'),
            preserve_default=False,
        ),
    ]
