# Generated by Django 3.1.5 on 2021-01-19 14:42

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0008_auto_20210119_1541'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deposit',
            name='take_in_before_give_out',
        ),
        migrations.RemoveConstraint(
            model_name='deposit',
            name='inactive_deposit_no_in_datetime',
        ),
        migrations.RemoveConstraint(
            model_name='issue',
            name='give_out_before_take_in',
        ),
        migrations.AddConstraint(
            model_name='deposit',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('active', True), ('out_datetime__isnull', True)), models.Q(('active', False), ('out_datetime__isnull', False)), _connector='OR'), name='inactive_deposit_no_out_datetime'),
        ),
        migrations.AddConstraint(
            model_name='deposit',
            constraint=models.CheckConstraint(check=models.Q(in_datetime__lte=django.db.models.expressions.F('out_datetime')), name='take_in_deposit_before_give_out'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.CheckConstraint(check=models.Q(out_date__gte=django.db.models.expressions.F('in_date')), name='give_out_key_before_take_in'),
        ),
    ]
