# Generated by Django 3.1.5 on 2021-04-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0008_historicaldeposit_historicalissue_historicalperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperson',
            name='gdpr_consent',
            field=models.BooleanField(default=False, verbose_name='Zustimmung Datenverarbeitung'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='gdpr_consent',
            field=models.BooleanField(default=False, verbose_name='Zustimmung Datenverarbeitung'),
            preserve_default=False,
        ),
    ]
