# Generated by Django 3.1.5 on 2021-04-20 14:26

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0009_auto_20210412_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperson',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Kommentar'),
        ),
        migrations.AddField(
            model_name='person',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, null=True, region=None, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='private_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='Private Mail'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='person',
            name='private_email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Private Mail'),
        ),
    ]
