# Generated by Django 3.1.5 on 2021-01-19 14:49

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0009_auto_20210119_1542'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='issue',
            name='give_out_key_before_take_in',
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.CheckConstraint(check=models.Q(out_date__lte=django.db.models.expressions.F('in_date')), name='give_out_key_before_take_in'),
        ),
    ]
