# Generated by Django 3.1.5 on 2021-04-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0010_auto_20210420_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperson',
            name='private_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='Private Mail'),
        ),
        migrations.AlterField(
            model_name='person',
            name='private_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Private Mail'),
        ),
    ]
