# Generated by Django 3.0.7 on 2020-06-23 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0010_auto_20200623_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='door',
            name='doors',
        ),
        migrations.AddField(
            model_name='door',
            name='room',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='keys.Room'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='doors',
            field=models.ManyToManyField(related_name='leads_into', to='keys.Door'),
        ),
    ]
