# Generated by Django 3.1.5 on 2021-01-19 14:59

from django.db import migrations, models
import keys.validators


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0011_auto_20210119_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='out_method',
            field=models.CharField(choices=[('cash', 'Bar'), ('bank transfer', 'Überweisung')], max_length=64, null=True, verbose_name='Zahlungsmittel'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='in_date',
            field=models.DateField(null=True, validators=[keys.validators.present_or_max_10_days_ago], verbose_name='Rückgabedatum'),
        ),
    ]
