# Generated by Django 3.0.7 on 2020-06-23 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0011_auto_20200623_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='keys.Room'),
        ),
    ]
