# Generated by Django 3.1.5 on 2021-01-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0012_auto_20210119_1559'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deposit',
            name='inactive_deposit_has_out_datetime_out_method',
        ),
        migrations.AddConstraint(
            model_name='deposit',
            constraint=models.CheckConstraint(check=models.Q(('active', False), ('out_datetime__isnull', False), ('out_method__isnull', False)), name='inactive_deposit_has_out_datetime_out_method'),
        ),
    ]
