# Generated by Django 3.0.7 on 2020-06-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0012_auto_20200623_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='doors',
        ),
        migrations.AddField(
            model_name='door',
            name='connecting',
            field=models.BooleanField(default=False),
        ),
    ]
