# Generated by Django 3.0.7 on 2020-06-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0013_auto_20200623_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='connecting',
            field=models.BooleanField(default=False, verbose_name='Zwischentüre'),
        ),
    ]
