# Generated by Django 3.1.5 on 2021-01-26 20:41

from django.db import migrations, models
import keys.validators


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0014_auto_20210119_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5, validators=[keys.validators.validate_deposit_mail], verbose_name='Kautionsbetrag'),
        ),
        migrations.AddConstraint(
            model_name='deposit',
            constraint=models.CheckConstraint(check=models.Q(amount__gte=0), name='deposit_not_negative'),
        ),
    ]
