# Generated by Django 3.0.7 on 2020-06-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0014_auto_20200623_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='door',
            name='connecting',
        ),
        migrations.AddField(
            model_name='door',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
    ]
